name: Trigger auto deployment for container-app-onmo4foc6nejc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-onmo4foc6nejc-AutoDeployTrigger-10e23eb9-6f8b-4eba-82e3-ab2af8d6aefe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPONMO4FOC6NEJC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPONMO4FOC6NEJC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPONMO4FOC6NEJC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPONMO4FOC6NEJC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPONMO4FOC6NEJC_REGISTRY_PASSWORD }}
          containerAppName: container-app-onmo4foc6nejc
          resourceGroup: todonodejspgsqlgoogleauthb1e39d06
          imageToBuild: default/container-app-onmo4foc6nejc:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


